import { Inter } from "next/font/google";
import SideBarContainer from "@/components/ui/side-bar/side-bar";
import HeaderWrapper from "@/components/ui/header/header-wrapper";
import "@/app/globals.css";
import "@/build.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: " UDM INVENTORY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row items-start bg-blue-300">
          <>
            <SideBarContainer />
          </>
          <div className="w-full">
            <>
              <HeaderWrapper />
            </>
            <main className="h-[100dvh]">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
