import { Inter } from "next/font/google";
import SideBarContainer from "@/components/ui/side-bar/side-bar";
import HeaderWrapper from "@/components/ui/header/header-wrapper";
import "@/app/globals.css";
import "@/build.css";

import Wrapper from "@/components/ui/active-user-wrapper/wrapper";

export const metadata = {
  title: " UDM INVENTORY",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Wrapper>
      <div className="flex flex-row items-start">
        <>
          <SideBarContainer />
        </>
        <div className="flex w-full flex-col">
          <>
            <HeaderWrapper />
          </>
          <main className="h-[100dvh]">{children}</main>
        </div>
      </div>
    </Wrapper>
  );
}
